### ISSUE TITLE
poster TODOs

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproin-publications#1]
- [x] add information about "deployment" at DBIC (# of datasets, total size)
- [x] point to the dbic/QA
- [x] Work in progress section
      - full dates anonimization (will be available after DataLad 0.10 release)
      - adoption of "German way of thinking":
        - configurable tune ups for the specific study (renames to conform the naming spec)
        - be able to recreate any dataset from scratch (currently some required manual tune ups for split sessions etc)
- [x] automagic slicing of electrophys etc data into BIDS datasets
- [x] automated monitoring

Also report on current usage at DBIC
- [x] there is a screen on rolando where ncdu is running to see full size... but we have around 40 datasets now!

**Comment by mvdoc** [comment]
all done in a60867157dfa1a0a53ed722a67e1e2666fea6b99
